name: docbook
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/imgs/Appointment-1024.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
 

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/fonts/
     - assets/imgs/

  fonts:
   - family: Rabar_019
     fonts:
       - asset: assets/fonts/rabar19.ttf 

   - family: Rabar_032
     fonts:
      - asset: assets/fonts/rabar32.ttf

   - family: Rabar_033
     fonts:
       - asset: assets/fonts/rabar33.ttf
       
   - family: RudawRegular
     fonts:
      - asset: assets/fonts/rudawregular2.ttf